const data_en = [
  {
    logo: ["logos/acer.png"],
    "Onlajn servis": "Acer",
    "Pravno lice": "Acer Sales International SA",
    "Sedište pravnog lica": "Bioggio, Switzerland",
    Predstavnik: "Law Office Moravčević, Vojnović i Partneri AOD Beograd",
    "Adresa predstavnika": "Bulevar vojvode Bojovića br. 6-8, Beograd",
    "Mejl predstavnika": "office@schoenherr.rs",
  },

  {
    logo: ["logos/aicure.png"],
    "Onlajn servis": "AiCure",
    "Pravno lice": "AiCure LLC",
    "Sedište pravnog lica": "New York (New York), USA",
    Predstavnik: "Law Office Samardžić Oreški Grbović a.o.d.",
    "Adresa predstavnika": "Kondina 13, Beograd.",
    "Mejl predstavnika": "office@sog.rs",
  },

  {
    logo: ["logos/alibaba.png", "logos/aliexpress.png"],
    "Onlajn servis": "Alibaba, AliExpress",
    "Pravno lice": "Alibaba.com Singapore E-Commerce Private Limited",
    "Sedište pravnog lica": "Singapore",
    Predstavnik: "Law Office Karanović & Partners o.a.d. Beograd,",
    "Adresa predstavnika": "Resavska 23, Beograd",
    "Mejl predstavnika": "serbia@karanovicpartners.com",
  },

  {
    logo: ["logos/ariston.png"],
    "Onlajn servis": "Ariston",
    "Pravno lice": "Ariston Thermo Croatia d.o.o.",
    "Sedište pravnog lica": "Zagreb, Croatia",
    Predstavnik: "Law Office Janković Popović Mitić",
    "Adresa predstavnika": "Palmotićeva 16a, Beograd",
    "Mejl predstavnika": "office@jpm.rs",
  },
  {
    logo: ["logos/battlerite.png"],
    "Onlajn servis": "Battlerite",
    "Pravno lice": "Stunlock Studios AB",
    "Sedište pravnog lica": "Skövde, Sweden",
    Predstavnik: "Law Office Karanović & Partners o.a.d. Beograd,",
    "Adresa predstavnika": "Resavska 23, Beograd",
    "Mejl predstavnika": "local.representative@karanovicpartners.com",
  },
  {
    logo: ["logos/blood-hunt.png"],
    "Onlajn servis": "Bloodhunt",
    "Pravno lice": "Sharkmob AB",
    "Sedište pravnog lica": "Malmö, Sweden",
    Predstavnik: "Law Office Karanović & Partners o.a.d. Beograd,",
    "Adresa predstavnika": "Resavska 23, Beograd",
    "Mejl predstavnika": "local.representative@karanovicpartners.com",
  },

  {
    logo: ["logos/booking.png"],
    "Onlajn servis": "Booking",
    "Pravno lice": "Booking.com B.V.",
    "Sedište pravnog lica": "Amsterdam, The Netherlands",
    Predstavnik: "Law Office Mikijelj Janković i Bogdanović",
    "Adresa predstavnika": "Vlajkovićeva 28, Beograd.",
    "Mejl predstavnika": "office@mjb.rs",
  },
  {
    logo: ["logos/coca-cola.png"],
    "Onlajn servis": "Coca Cola",
    "Pravno lice":
      "SA Coca-Cola Services N.V. u sastavu The Coca-Cola Company grupe",
    "Sedište pravnog lica": "Brussels, Belgium",
    Predstavnik:
      "Attorney at law Ivana Ružičić (advokatska kancelarija PR Legal)",
    "Adresa predstavnika": "Studentski trg 10/4, Beograd",
    "Mejl predstavnika": "ivana.ruzicic@prlegal.rs",
  },
  {
    logo: ["logos/corvusinfo.png"],
    "Onlajn servis": "CorvusInfo",
    "Pravno lice": "CorvusInfo d.o.o. ",
    "Sedište pravnog lica": "Zagreb, Croatia",
    Predstavnik: "Nataša Pepić",
    //"Adresa predstavnika": "",
    "Mejl predstavnika": "zastitnik@kimtec.rs",
  },
  {
    logo: ["logos/esky.png"],
    "Onlajn servis": "ESky",
    "Pravno lice": "eSky.pl S.A.",
    "Sedište pravnog lica": "Katowice, Poland",
    Predstavnik: "Attorney at law Tijana Žunić Marić",
    "Adresa predstavnika": "Pozorišni trg 7/6A,\nNovi Sad, ",
    "Mejl predstavnika": "tijana.zunic@zuniclaw.com",
  },
  {
    logo: ["logos/google.png", "logos/youtube.png"],
    "Onlajn servis":
      "Google servisi (Search, Gmail...), YouTube, Blogger, Vevo",
    "Pravno lice": "Google LLC",
    "Sedište pravnog lica": "Mountain View (California), USA",
    Predstavnik: " Law Office BDK Advokati",
    "Adresa predstavnika": "Bulevar kralja Aleksandra 28, Beograd.",
    "Mejl predstavnika": "office@bdkadvokati.com",
  },
  {
    logo: ["logos/la_prairie.png"],
    "Onlajn servis": "La Prairie",
    "Pravno lice": "La Prairie Group AG",
    "Sedište pravnog lica": "Volketswil, Switzerland",
    Predstavnik: "Law Office Karanović & Partners,",
    "Adresa predstavnika": "Resavska 23, Beograd",
    "Mejl predstavnika": "serbia@karanovicpartners.com",
  },
  {
    logo: ["logos/netflix.png"],
    "Onlajn servis": "Netflix",
    "Pravno lice": "Netflix International B.V. ",
    "Sedište pravnog lica": "Amsterdam, The Nethelands",
    Predstavnik: "Law Office Mikijelj Janković i Bogdanović",
    "Adresa predstavnika": "Vlajkovićeva 28, Beograd.",
    "Mejl predstavnika": "office@mjb.rs",
  },
  {
    logo: ["logos/yahoo!.png"],
    "Onlajn servis": "Yahoo ",
    "Pravno lice": "Oath Inc. (Verizon Communications) ",
    "Sedište pravnog lica": "New York (New York), USA",
    Predstavnik: "Law Office Karanović & Partners,",
    "Adresa predstavnika": "Resavska 23, Beograd",
    "Mejl predstavnika": "serbia@karanovicpartners.com",
  },
  {
    logo: ["logos/orsay.png"],
    "Onlajn servis": "Orsay",
    "Pravno lice": "Orsay GmbH",
    "Sedište pravnog lica": "Willstätt-Sand, Germany",
    Predstavnik: "Ordiser doo Beograd",
    "Adresa predstavnika": "Jurija Gagarina 16, Beograd",
    "Mejl predstavnika": "service@orsay.com",
  },
  {
    logo: ["logos/pubg.png"],
    "Onlajn servis": "PUBG Mobile",
    "Pravno lice": "Proxima Beta Pte. LTD (Tencent group)",
    "Sedište pravnog lica": "Singapore",
    Predstavnik: "Law Office Karanović & Partners,",
    "Adresa predstavnika": "Resavska 23, Beograd",
    "Mejl predstavnika": "serbia@karanovicpartners.com",
  },

  {
    logo: ["logos/snapchat.png"],
    "Onlajn servis": "Snapchat",
    "Pravno lice": "Snap Inc.",
    "Sedište pravnog lica": "Santa Monica (California), USA",
    Predstavnik: "Law Office Živković Samardžić",
    "Adresa predstavnika": "Makedonska 30, Beograd",
    "Mejl predstavnika": "office@zslaw.rs",
  },
  {
    logo: ["logos/spotify.png"],
    "Onlajn servis": "Spotify",
    "Pravno lice": "Spotify AB",
    "Sedište pravnog lica": "Stockholm, Sweden",
    Predstavnik: "Law Office Karanović & Partners,",
    "Adresa predstavnika": "Resavska 23, Beograd",
    "Mejl predstavnika": "serbia@karanovicpartners.com",
  },

  {
    logo: ["logos/toptal.png"],
    "Onlajn servis": "Toptal",
    "Pravno lice": "TOPTAL LLC",
    "Sedište pravnog lica": "San Francisco (California), USA",
    Predstavnik: "Snežana Marković",
    "Adresa predstavnika": "",
    "Mejl predstavnika": "serbianprivacyteam@toptal.com",
  },
  {
    logo: ["logos/upwork.png"],
    "Onlajn servis": "Upwork",
    "Pravno lice": "Upwork Global Inc.",
    "Sedište pravnog lica": "Santa Clara (California), USA",
    Predstavnik: "Law Office Karanović & Partners,",
    "Adresa predstavnika": "Resavska 23, Beograd",
    "Mejl predstavnika": "serbia@karanovicpartners.com",
  },

  {
    logo: ["logos/viber.png"],
    "Onlajn servis": "Viber",
    "Pravno lice": "Viber Media S.a.r.l. ",
    "Sedište pravnog lica": "Luxembourg",
    Predstavnik: "Law Office Marković Vukotić Jovković",
    "Adresa predstavnika": "Vlajkovićeva 12, Beograd.",
    "Mejl predstavnika": "office@mvj.rs",
  },
  {
    logo: ["logos/wechat.png"],
    "Onlajn servis": "WeChat",
    "Pravno lice": "WeChat International Pte. LTD (Tencent group)",
    "Sedište pravnog lica": "Singapore",
    Predstavnik: "Law Office Karanović & Partners,",
    "Adresa predstavnika": "Resavska 23, Beograd",
    "Mejl predstavnika": "serbia@karanovicpartners.com",
  },
  {
    logo: ["logos/wizzair.png"],
    "Onlajn servis": "Wizz Air",
    "Pravno lice": "Wizz Air Hungary Airlines Limited",
    "Sedište pravnog lica": "Budapest, Hungary",
    Predstavnik: "Attorney at law Igor V. Denčić",
    "Adresa predstavnika": "Terazije 8, Beograd",
    "Mejl predstavnika": "office@dencic.rs",
  },
  {
    logo: ["logos/yandex.png"],
    "Onlajn servis": "Yandex servisi",
    "Pravno lice": "Yandex LLC",
    "Sedište pravnog lica": "Moscow, Russia",
    Predstavnik: "Law Office Živković Samardžić",
    "Adresa predstavnika": "Makedonska 30, Beograd",
    "Mejl predstavnika": "office@zslaw.rs",
  },
  {
    logo: ["logos/airbnb.png"],
    "Onlajn servis": "Airbnb",
    "Pravno lice": "Airbnb, Inc.",
    "Sedište pravnog lica": "San Francisco (California), USA",
    // Predstavnik: "X",
    // "Adresa predstavnika": "X",
    // "Mejl predstavnika": "X",
  },
  {
    logo: ["logos/amazon.png", "logos/amazonprimevideo.png", "logos/aws.png"],
    "Onlajn servis":
      "Amazon.com, Amazon Alexa, Amazon Prime      Video, Amazon Web Services...",
    "Pravno lice": "Amazon, Inc.",
    "Sedište pravnog lica": "Seattle (Washington), USA",
    // Predstavnik: "X",
    // "Adresa predstavnika": "X",
    // "Mejl predstavnika": "X",
  },
  {
    logo: ["logos/fb.png", "logos/instagram.png", "logos/whatsapp.png"],
    "Onlajn servis": "Facebook, Instagram, WhatsApp",
    "Pravno lice": "Facebook, Inc.",
    "Sedište pravnog lica": "Menlo Park (California), USA",
    //Predstavnik: "X",
    //"Adresa predstavnika": "X",
    //"Mejl predstavnika": "X",
  },
  {
    logo: ["logos/godaddy.png"],
    "Onlajn servis": "GoDaddy",
    "Pravno lice": "GoDaddy, Inc.",
    "Sedište pravnog lica": "Scottsdale (Arizona), USA",
    // Predstavnik: "X",
    //"Adresa predstavnika": "X",
    //"Mejl predstavnika": "X",
  },

  {
    logo: ["logos/ryanair.png"],
    "Onlajn servis": "Ryanair",
    "Pravno lice": "Ryanair DAC",
    "Sedište pravnog lica": "Dublin, Republic of Ireland",
    // Predstavnik: "X",
    // "Adresa predstavnika": "X",
    // "Mejl predstavnika": "X",
  },
  {
    logo: ["logos/twitch.png"],
    "Onlajn servis": "Twitch",
    "Pravno lice": "Twitch Interactive, Inc.",
    "Sedište pravnog lica": "San Francisco (California), USA",
    // Predstavnik: "X",
    // "Adresa predstavnika": "X",
    // "Mejl predstavnika": "X",
  },
  {
    logo: ["logos/twitter.png"],
    "Onlajn servis": "Twitter",
    "Pravno lice": "Twitter, Inc.",
    "Sedište pravnog lica": "San Francisco (California), USA",
    // Predstavnik: "X",
    // "Adresa predstavnika": "X",
    // "Mejl predstavnika": "X",
  },
];

export default data_en;
